#!/usr/bin/env python3
"""Regenerate the generated blocks in README.md.

Two of them, both between markers:

  STAGE-COST  the current stage's cost above baseline, one line.
  COST-TABLE  one row per stage, so the whole progression reads on one screen.

Figures come from measurements/<slug>.csv and the stage metadata from
measurements/stages.tsv. Nothing here is hand-maintained: a figure quoted in
prose is a figure that goes stale silently, so every number in the README is
written by this script.

    python3 scripts/gen-cost-table.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
MEAS = ROOT / "measurements"
README = ROOT / "README.md"

BASE_SLUG = "Baseline"

# Flash is the read-only image plus the initialisers copied out of it. RAM is
# everything the image reserves: .bss — which already contains the FreeRTOS heap
# array, the mbedTLS buffer and every task stack — plus .data, which is copied
# into RAM at startup. Adding heap_used to that would count the heap twice.
DERIVED = [
    ("Flash", lambda d: d["flash_text"] + d["flash_data"]),
    ("RAM", lambda d: d["flash_data"] + d["static_bss"]),
]
RAW_KEYS = ["flash_text", "flash_data", "static_bss"]


def load_csv(slug):
    values = {}
    for line in (MEAS / f"{slug}.csv").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition(",")
        if key in RAW_KEYS:
            values[key] = int(value)
    missing = [k for k in RAW_KEYS if k not in values]
    if missing:
        raise SystemExit(f"{slug}.csv missing keys: {missing}")
    return values


def load_stages():
    rows = []
    for line in (MEAS / "stages.tsv").read_text(encoding="utf-8").splitlines():
        line = line.rstrip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 3:
            raise SystemExit(f"stages.tsv row must be slug<TAB>name<TAB>what-it-gives-you: {line!r}")
        rows.append(parts)
    return rows


def replace_block(text, marker, body):
    block = f"<!-- {marker}:START (generated by scripts/gen-cost-table.py — do not edit by hand) -->\n\n{body}\n\n<!-- {marker}:END -->"
    new_text, n = re.subn(rf"<!-- {marker}:START.*?{marker}:END -->", lambda _: block, text, count=1, flags=re.S)
    if n != 1:
        raise SystemExit(f"{marker} markers not found in README.md")
    return new_text


def main():
    # The baseline is named rather than inferred from list position: every figure
    # in the table is a delta above it, so the wrong reference is wrong silently.
    stages = load_stages()
    if not any(slug == BASE_SLUG for slug, _, _ in stages):
        raise SystemExit(f"measurements/stages.tsv has no {BASE_SLUG} row")
    if not (MEAS / f"{BASE_SLUG}.csv").exists():
        raise SystemExit(f"measurements/{BASE_SLUG}.csv is required: every figure is a delta above it")

    pending = [slug for slug, _, _ in stages if slug != BASE_SLUG and not (MEAS / f"{slug}.csv").exists()]
    stages = [row for row in stages if row[0] not in pending]

    base = {name: fn(load_csv(BASE_SLUG)) for name, fn in DERIVED}

    header = ["Stage", "What it gives you"] + [name for name, _ in DERIVED]
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]
    for slug, name, gives in stages:
        cur = load_csv(slug)
        cells = [name, gives]
        cells += ["—" for _ in DERIVED] if slug == BASE_SLUG else [f"{fn(cur) - base[n]:+,}" for n, fn in DERIVED]
        lines.append("| " + " | ".join(cells) + " |")
    table = "\n".join(lines) + "\n\n*Deltas are bytes above the baseline, which is itself " + ", ".join(
        f"{name} {base[name]:,} B" for name, _ in DERIVED
    ) + ".*"

    # The current stage is the last frozen one. At the baseline there is no cost
    # above baseline to state, and saying "+0" would imply there could have been.
    slug, name, _ = stages[-1]
    if slug == BASE_SLUG:
        cost = "This is the baseline itself: " + ", ".join(f"{n} {base[n]:,} B" for n, _ in DERIVED) + "."
    else:
        cur = load_csv(slug)
        cost = "**Cost above baseline: " + ", ".join(f"{n} {fn(cur) - base[n]:+,} B" for n, fn in DERIVED) + ".**"

    text = README.read_text(encoding="utf-8")
    text = replace_block(text, "STAGE-COST", cost)
    text = replace_block(text, "COST-TABLE", table)
    README.write_text(text, encoding="utf-8", newline="\n")

    print(f"updated README for stage '{name}' ({len(stages)} stage(s) in the table)")
    if pending:
        print(f"not yet frozen, so left out: {', '.join(pending)}")


if __name__ == "__main__":
    main()
